vault: "/Users/thierrycrouzet/Documents/ObsidianLocal/text/tcrouzet"
vault_img: "_i/"
export: "/Users/thierrycrouzet/Documents/staticT"
images_dir: "/images_tc/"
title: "Thierry Crouzet"
domain: "https://tcrouzet.com/"
template: "tcrouzet"
analytics: False
version: 3

tagsT:
  - id: netlitterature
    title: "NetLittérature"
  - id: cuisine
    title: "Cuisine"


tags:
  netlitterature:
    title: "NetLittérature"
  cuisine:
    title: "Cuisine"
