build: 0 #O: No update 1:Update new post only 2:update from scratch

vault: "/Users/thierrycrouzet/Documents/ObsidianLocal/text/tcrouzet"
vault_img: "_i/"
export: "/Users/thierrycrouzet/Documents/staticT"
images_dir: "/images_tc/"
title: "Thierry Crouzet"
domain: "https://tcrouzet.com/"
template: "tcrouzet"
analytics: False
version: 0 #0 dynamic random version for testing only

tags:
  series:
    title: "Séries"
  carnets:
    title: "Carnets"
    url: "carnet-de-route"
  velo:
    title: "Vélo"
    url: "borntobike"
  ecriture:
    title: "Écriture"
  edition:
    title: "Édition"
  netlitterature:
    title: "NetLittérature"
  netculture:
    title: "NetCulture"
  cuisine:
    title: "Cuisine"
