build: 1 #O: No update 1:Update new post only 2:update from scratch
version: 0 #0 dynamic random version for testing only (no minification)

vault: "/Users/thierrycrouzet/Documents/ObsidianLocal/text/tcrouzet"
vault_img: "_i/"
export: "/Users/thierrycrouzet/Documents/staticT"
images_dir: "/images_tc/"
feeds_dir: "/feeds/"
title: "Thierry Crouzet"
domain: "https://tcrouzet.com/"
author: "Thierry Crouzet"
email: tc@tcrouzet.com
template: "tcrouzet"
analytics: False

# Listes des dossiers où sont les pages qui se retrouvent à la racine du site
pages:
 - "page"
 - "books"

tags:
  series:
    title: "Séries"
  book:
    title: "Bibliographie"
    url: "/bibliographie"
  carnets:
    title: "Carnets"
    url: "carnet-de-route"
  velo:
    title: "Vélo"
    url: "borntobike"
  ecriture:
    title: "Écriture"
  edition:
    title: "Édition"
  netlitterature:
    title: "NetLittérature"
  netculture:
    title: "NetCulture"
  cuisine:
    title: "Cuisine"
